version: "~> 1.0"
os: linux
arch:
- amd64
language: python
python:
- '3.6'
services:
- docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: s66MWlPsJVN0XGc+/ls/KdXah0tvdd8Z8ukqnUTrcTOkPSYS4OR8MNaSUxmxSaADNNxZwstVXN4yz5g+RdUWGBASz0RH9083Z3wNjHWM1s6J2f1fia3Kr4G8u+dRcNpNQoUqk1ti9u54/iZFMQBDjCcRgR28guQ6UruoG4FWrZXQ+zV/qrteWf/AVBPkO6wpyZWEY21KsysA81ktR2NxTMmxpA+JO7OS3afP2Kec1T6usa8mpYj7Wgn/NJyeKnAfEA2Cj/R7t3VmcXHgLNXQkxQedixOIKrOjoYKSbIUxB5CUsozWUxqKYruZ934tCPdSTvjqOynojdTkaRClPvreLv0JtaPwcoU7AqEqjgjM85m530barM37zV1Vj9Vgx5ppMRTWZqCnugL8PL0VtTsJQB0TYPuJkZRu1NLu3257tT8Bunj3ywfrX+udOf3t542jjwrf2BmXdx+y6D/rawvtlUiKsEJi7V53upybMV9CyU6fxyyG2mk7AbUniTX3OSWV0wC6Cv0g8wLO+7G2tpvXPCaFiOt5fMpWKPf8kFqp0u8nxbPTXrIJjcNgMeuPjAHLKBA4fBdxDPBNQBgD5RSuVWRCE8s7tEH3ynUsj7v/vETuqM/napG0j56K/w09a7ic+3xtNuCdWncidh20BnQn4HmMlDocyU4oLdf/P8lksI=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
install:
- pip install -r requirements.txt
- ansible-galaxy install -r requirements.yml -f
# - curl -Lo /tmp/travis_after_all.py https://raw.github.com/ckaserer/travis_after_all/master/travis_after_all.py
- curl -Lo merge.sh https://raw.githubusercontent.com/ckaserer/git-merge-script/master/merge.sh
- chmod a+x merge.sh
env:
  global:
  - secure: H10+AwtghG91i2CNTlnmOSR0P5ZY/ddmVSeGexUwvGVRxSO2tlGQZMoTCjOPXMMFnmwbRWpJCyhoYicky/YE5FHd4XUE/EBdmuDg78BBeAz5tYblxXHsvhQbDA50KybEa/hwSakopRwbMTeGPg0ADCZfzitLFXQR6Z+tyNgBSpZ1TazO8qWm+FIaNOrmpOS4ui1WSefxEyODDyLWF82DHDysXdqJ/EbNZoWe2LFIBRWsPiW6hYEQMO3emdEUp4gSscYo+u2eDFHU5zZ6SgWQIriF9bjL37oI8LRCPKrxybvSTgvr6yWxzQcb6QHvtlSSjohJWDVFnO3XDWAxeJ3B7tZQ12bYRPmphyuCfMgxRWYk3y7h1FfRMSlpnGEJAwMlNv6dNj9/MzuaFTnCytcsRneDSM4yWznxketzWOv1DuM7wKJf6sn/zHpoTHvcFT6O/CvsffTAzZOwfGVONl3FBM+rmY2iFqzSJYX/bZ8RuIEeXA1CLpqR8E+O5dD9MaYMyLHjfRktLi8vpaEwgktaUtZVR5rF2SuwFhED+KFijAgrYBjOMEcTO5tZ04t1eO22L93tVtm2kVQHRHgxJdRp90/UWnAfaeAn5w5uoZKSRy02i3x3pFLt3BzOu4nybEgTQ0v65ChlKkTkKFEC8IUrJiIZCmImR03FupjKfaVZXXg=
script:
- docker run --rm -d --name instance --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $(pwd):/mnt --tmpfs /run --tmpfs /tmp geerlingguy/docker-debian10-ansible /lib/systemd/systemd
- docker exec -it instance ansible-galaxy install -r /mnt/requirements.yml
- docker exec -it instance ansible-playbook /mnt/playbook.yml -i /mnt/hosts.ini --extra-vars arch=${TRAVIS_CPU_ARCH} --skip-tags notest 
after_success:
  - BRANCHES_TO_MERGE_REGEX='^develop' BRANCH_TO_MERGE_INTO=master ./merge.sh
