- hosts: gitlab_runner
  become: true
  pre_tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:

    - name: Set hostname to gitlab-runner
      hostname:
        name: gitlab-runner
      tags:
        - notest

    - name: Install git
      apt:
        name: git

    - name: Include ckaserer.gitlab_runner
      include_role:
        name: ckaserer.gitlab_runner
      vars:
        architecture: "{{ arch }}"
    
    - name: Include ckaserer.dhcpcd
      include_role:
        name: ckaserer.dhcpcd
      vars:
        dhcpcd_interface: "eth0"
        dhcpcd_ip_address: "10.0.0.2/24"
        reboot: false 
